crud_jobs/config/routes.rb
CrudJobs::Engine.routes.draw do
  resources :delayed_jobs
end

crud_jobs/app/models/crud_jobs/application_record.rb
module CrudJobs
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

crud_jobs/app/models/crud_jobs/delayed_job.rb
module CrudJobs
  class DelayedJob < ApplicationRecord
  end
end

crud_jobs/app/controllers/crud_jobs/application_controller.rb
module CrudJobs
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

crud_jobs/app/controllers/crud_jobs/delayed_jobs_controller.rb
require_dependency "crud_jobs/application_controller"

module CrudJobs
  class DelayedJobsController < ApplicationController
    before_action :set_delayed_job, only: [:show, :edit, :update, :destroy]

    # GET /delayed_jobs
    def index
      @delayed_jobs = CrudJobs::DelayedJob.all
    end

    # GET /delayed_jobs/1
    def show
    end

    # GET /delayed_jobs/new
    def new
      @delayed_job = CrudJobs::DelayedJob.new
    end

    # GET /delayed_jobs/1/edit
    def edit
    end

    # POST /delayed_jobs
    def create
      @delayed_job = CrudJobs::DelayedJob.new(delayed_job_params)

      if @delayed_job.save
        redirect_to @delayed_job, notice: 'Delayed job was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /delayed_jobs/1
    def update
      if @delayed_job.update(delayed_job_params)
        redirect_to @delayed_job, notice: 'Delayed job was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /delayed_jobs/1
    def destroy
      @delayed_job.destroy
      redirect_to delayed_jobs_url, notice: 'Delayed job was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_delayed_job
        @delayed_job = CrudJobs::DelayedJob.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def delayed_job_params
        params.fetch(:delayed_job, {})
      end
  end
end

crud_jobs/app/helpers/crud_jobs/application_helper.rb
module CrudJobs
  module ApplicationHelper
  end
end

crud_jobs/app/helpers/crud_jobs/delayed_jobs_helper.rb
module CrudJobs
  module DelayedJobsHelper
  end
end

crud_jobs/app/views/crud_jobs/delayed_jobs/_form.html.erb
<%= form_with(model: delayed_job, local: true) do |form| %>
  <% if delayed_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delayed_job.errors.count, "error") %> prohibited this delayed_job from being saved:</h2>

      <ul>
      <% delayed_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

crud_jobs/app/views/crud_jobs/delayed_jobs/edit.html.erb
<h1>Editing Delayed Job</h1>

<%= render 'form', delayed_job: @delayed_job %>

<%= link_to 'Show', @delayed_job %> |
<%= link_to 'Back', delayed_jobs_path %>

crud_jobs/app/views/crud_jobs/delayed_jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Delayed Jobs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delayed_jobs.each do |delayed_job| %>
      <tr>
        <td><%= link_to 'Show', delayed_job %></td>
        <td><%= link_to 'Edit', edit_delayed_job_path(delayed_job) %></td>
        <td><%= link_to 'Destroy', delayed_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delayed Job', new_delayed_job_path %>

crud_jobs/app/views/crud_jobs/delayed_jobs/new.html.erb
<h1>New Delayed Job</h1>

<%= render 'form', delayed_job: @delayed_job %>

<%= link_to 'Back', delayed_jobs_path %>

crud_jobs/app/views/crud_jobs/delayed_jobs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_delayed_job_path(@delayed_job) %> |
<%= link_to 'Back', delayed_jobs_path %>

crud_jobs/app/views/layouts/crud_jobs/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud jobs</title>
  <%= stylesheet_link_tag    "crud_jobs/application", media: "all" %>
  <%= javascript_include_tag "crud_jobs/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>